Test suite fixes and move test coverage at the end

diff --git a/tests/aggregate-results b/tests/aggregate-results
--- a/tests/aggregate-results
+++ b/tests/aggregate-results
@@ -1,6 +1,7 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Copyright (c) 2008-2012 Git project
+#               2017 Alexandre PUJOL <alexandre@pujol.io>.
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -14,6 +15,19 @@
 #
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see http://www.gnu.org/licenses/ .
+
+COVERAGE="true"
+if [[ "$COVERAGE" == "true" ]]; then
+	KCOV="$(which kcov)"
+	if [[ ! -e "$KCOV" ]]; then
+		echo "Could not find kcov command"
+		exit 1
+	fi
+	TMP="/tmp/pass-tomb"
+	COVERED=($(find $TMP/*.sh -maxdepth 0 -type d))
+	[[ -z "$TRAVIS_JOB_ID" ]] || TRAVIS="--coveralls-id=$TRAVIS_JOB_ID"
+	"$KCOV" $TRAVIS --merge "$TMP/kcov" "${COVERED[@]}"
+fi
 
 failed_tests=
 fixed=0
